--------------------------------------------------------
--  파일이 생성됨 - 화요일-9월-29-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "SCOTT"."BOARD" 
   (	"BOARD_NUM" NUMBER, 
	"BOARD_ID" VARCHAR2(50 BYTE), 
	"BOARD_SUBJECT" VARCHAR2(100 BYTE), 
	"BOARD_CONTENT" VARCHAR2(2000 BYTE), 
	"BOARD_FILE" VARCHAR2(100 BYTE), 
	"BOARD_RE_REF" NUMBER, 
	"BOARD_RE_LEV" NUMBER, 
	"BOARD_RE_SEQ" NUMBER, 
	"BOARD_COUNT" NUMBER, 
	"BOARD_DATE" DATE, 
	"BOARD_PARENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SCOTT.BOARD
SET DEFINE OFF;
Insert into SCOTT.BOARD (BOARD_NUM,BOARD_ID,BOARD_SUBJECT,BOARD_CONTENT,BOARD_FILE,BOARD_RE_REF,BOARD_RE_LEV,BOARD_RE_SEQ,BOARD_COUNT,BOARD_DATE,BOARD_PARENT) values (1,'admin','테스트','테스트글 입니다','logo_footer1.jpg',1,null,null,6,to_date('20/09/28','RR/MM/DD'),0);
Insert into SCOTT.BOARD (BOARD_NUM,BOARD_ID,BOARD_SUBJECT,BOARD_CONTENT,BOARD_FILE,BOARD_RE_REF,BOARD_RE_LEV,BOARD_RE_SEQ,BOARD_COUNT,BOARD_DATE,BOARD_PARENT) values (4,'admin','테스트','테스트글입니다',null,4,null,null,0,to_date('20/09/28','RR/MM/DD'),0);
Insert into SCOTT.BOARD (BOARD_NUM,BOARD_ID,BOARD_SUBJECT,BOARD_CONTENT,BOARD_FILE,BOARD_RE_REF,BOARD_RE_LEV,BOARD_RE_SEQ,BOARD_COUNT,BOARD_DATE,BOARD_PARENT) values (3,'admin','테스트','테스트글입니다',null,3,null,null,1,to_date('20/09/28','RR/MM/DD'),0);
Insert into SCOTT.BOARD (BOARD_NUM,BOARD_ID,BOARD_SUBJECT,BOARD_CONTENT,BOARD_FILE,BOARD_RE_REF,BOARD_RE_LEV,BOARD_RE_SEQ,BOARD_COUNT,BOARD_DATE,BOARD_PARENT) values (5,'admin','테스트','테스트글입니다',null,5,null,null,0,to_date('20/09/28','RR/MM/DD'),0);
Insert into SCOTT.BOARD (BOARD_NUM,BOARD_ID,BOARD_SUBJECT,BOARD_CONTENT,BOARD_FILE,BOARD_RE_REF,BOARD_RE_LEV,BOARD_RE_SEQ,BOARD_COUNT,BOARD_DATE,BOARD_PARENT) values (6,'admin','테스트','테스트글입니다',null,6,null,null,0,to_date('20/09/28','RR/MM/DD'),0);
Insert into SCOTT.BOARD (BOARD_NUM,BOARD_ID,BOARD_SUBJECT,BOARD_CONTENT,BOARD_FILE,BOARD_RE_REF,BOARD_RE_LEV,BOARD_RE_SEQ,BOARD_COUNT,BOARD_DATE,BOARD_PARENT) values (7,'admin','테스트','테스트글입니다',null,7,null,null,0,to_date('20/09/28','RR/MM/DD'),0);
Insert into SCOTT.BOARD (BOARD_NUM,BOARD_ID,BOARD_SUBJECT,BOARD_CONTENT,BOARD_FILE,BOARD_RE_REF,BOARD_RE_LEV,BOARD_RE_SEQ,BOARD_COUNT,BOARD_DATE,BOARD_PARENT) values (8,'admin','테스트','테스트글입니다',null,8,null,null,0,to_date('20/09/28','RR/MM/DD'),0);
Insert into SCOTT.BOARD (BOARD_NUM,BOARD_ID,BOARD_SUBJECT,BOARD_CONTENT,BOARD_FILE,BOARD_RE_REF,BOARD_RE_LEV,BOARD_RE_SEQ,BOARD_COUNT,BOARD_DATE,BOARD_PARENT) values (9,'admin','테스트','테스트글입니다',null,9,null,null,0,to_date('20/09/28','RR/MM/DD'),0);
Insert into SCOTT.BOARD (BOARD_NUM,BOARD_ID,BOARD_SUBJECT,BOARD_CONTENT,BOARD_FILE,BOARD_RE_REF,BOARD_RE_LEV,BOARD_RE_SEQ,BOARD_COUNT,BOARD_DATE,BOARD_PARENT) values (10,'admin','테스트','테스트글입니다',null,10,null,null,0,to_date('20/09/28','RR/MM/DD'),0);
Insert into SCOTT.BOARD (BOARD_NUM,BOARD_ID,BOARD_SUBJECT,BOARD_CONTENT,BOARD_FILE,BOARD_RE_REF,BOARD_RE_LEV,BOARD_RE_SEQ,BOARD_COUNT,BOARD_DATE,BOARD_PARENT) values (11,'admin','테스트','테스트글입니다',null,11,null,null,0,to_date('20/09/28','RR/MM/DD'),0);
Insert into SCOTT.BOARD (BOARD_NUM,BOARD_ID,BOARD_SUBJECT,BOARD_CONTENT,BOARD_FILE,BOARD_RE_REF,BOARD_RE_LEV,BOARD_RE_SEQ,BOARD_COUNT,BOARD_DATE,BOARD_PARENT) values (12,'admin','테스트','테스트글입니다',null,12,null,null,0,to_date('20/09/28','RR/MM/DD'),0);
Insert into SCOTT.BOARD (BOARD_NUM,BOARD_ID,BOARD_SUBJECT,BOARD_CONTENT,BOARD_FILE,BOARD_RE_REF,BOARD_RE_LEV,BOARD_RE_SEQ,BOARD_COUNT,BOARD_DATE,BOARD_PARENT) values (13,'admin','테스트','테스트글입니다',null,13,null,null,0,to_date('20/09/28','RR/MM/DD'),0);
Insert into SCOTT.BOARD (BOARD_NUM,BOARD_ID,BOARD_SUBJECT,BOARD_CONTENT,BOARD_FILE,BOARD_RE_REF,BOARD_RE_LEV,BOARD_RE_SEQ,BOARD_COUNT,BOARD_DATE,BOARD_PARENT) values (14,'admin','테스트','테스트글입니다',null,14,null,null,0,to_date('20/09/28','RR/MM/DD'),0);
Insert into SCOTT.BOARD (BOARD_NUM,BOARD_ID,BOARD_SUBJECT,BOARD_CONTENT,BOARD_FILE,BOARD_RE_REF,BOARD_RE_LEV,BOARD_RE_SEQ,BOARD_COUNT,BOARD_DATE,BOARD_PARENT) values (15,'admin','테스트','테스트글입니다',null,15,null,null,0,to_date('20/09/28','RR/MM/DD'),0);
Insert into SCOTT.BOARD (BOARD_NUM,BOARD_ID,BOARD_SUBJECT,BOARD_CONTENT,BOARD_FILE,BOARD_RE_REF,BOARD_RE_LEV,BOARD_RE_SEQ,BOARD_COUNT,BOARD_DATE,BOARD_PARENT) values (16,'admin','테스트','테스트글입니다',null,16,null,null,0,to_date('20/09/28','RR/MM/DD'),0);
Insert into SCOTT.BOARD (BOARD_NUM,BOARD_ID,BOARD_SUBJECT,BOARD_CONTENT,BOARD_FILE,BOARD_RE_REF,BOARD_RE_LEV,BOARD_RE_SEQ,BOARD_COUNT,BOARD_DATE,BOARD_PARENT) values (17,'admin','테스트','테스트글입니다',null,17,null,null,0,to_date('20/09/28','RR/MM/DD'),0);
Insert into SCOTT.BOARD (BOARD_NUM,BOARD_ID,BOARD_SUBJECT,BOARD_CONTENT,BOARD_FILE,BOARD_RE_REF,BOARD_RE_LEV,BOARD_RE_SEQ,BOARD_COUNT,BOARD_DATE,BOARD_PARENT) values (18,'admin','테스트','테스트글입니다',null,18,null,null,0,to_date('20/09/28','RR/MM/DD'),0);
Insert into SCOTT.BOARD (BOARD_NUM,BOARD_ID,BOARD_SUBJECT,BOARD_CONTENT,BOARD_FILE,BOARD_RE_REF,BOARD_RE_LEV,BOARD_RE_SEQ,BOARD_COUNT,BOARD_DATE,BOARD_PARENT) values (19,'admin','테스트','테스트글입니다',null,19,null,null,0,to_date('20/09/28','RR/MM/DD'),0);
Insert into SCOTT.BOARD (BOARD_NUM,BOARD_ID,BOARD_SUBJECT,BOARD_CONTENT,BOARD_FILE,BOARD_RE_REF,BOARD_RE_LEV,BOARD_RE_SEQ,BOARD_COUNT,BOARD_DATE,BOARD_PARENT) values (20,'admin','테스트글(수정)','테스트글입니다','logo_footer2.jpg',20,null,null,4,to_date('20/09/29','RR/MM/DD'),0);
--------------------------------------------------------
--  DDL for Index PK_BOARD
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."PK_BOARD" ON "SCOTT"."BOARD" ("BOARD_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY ("BOARD_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SCOTT"."BOARD" MODIFY ("BOARD_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BOARD" ADD CONSTRAINT "PK_BOARD_ID" FOREIGN KEY ("BOARD_ID")
	  REFERENCES "SCOTT"."MEMBERS" ("ID") ENABLE;
