--------------------------------------------------------
--  파일이 생성됨 - 화요일-9월-29-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOARD_COMMENT
--------------------------------------------------------

  CREATE TABLE "SCOTT"."BOARD_COMMENT" 
   (	"COMMENT_NUM" NUMBER, 
	"COMMENT_BOARD" NUMBER, 
	"COMMENT_ID" VARCHAR2(15 BYTE), 
	"COMMENT_DATE" DATE, 
	"COMMENT_PARENT" NUMBER, 
	"COMMENT_CONTENT" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SCOTT.BOARD_COMMENT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_COMMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."PK_COMMENT" ON "SCOTT"."BOARD_COMMENT" ("COMMENT_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BOARD_COMMENT
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BOARD_COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY ("COMMENT_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SCOTT"."BOARD_COMMENT" MODIFY ("COMMENT_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARD_COMMENT" MODIFY ("COMMENT_BOARD" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARD_COMMENT" MODIFY ("COMMENT_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BOARD_COMMENT
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BOARD_COMMENT" ADD CONSTRAINT "FK_COMMENT" FOREIGN KEY ("COMMENT_BOARD")
	  REFERENCES "SCOTT"."BOARD" ("BOARD_NUM") ENABLE;
