--------------------------------------------------------
--  파일이 생성됨 - 화요일-9월-29-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CHAMPION
--------------------------------------------------------

  CREATE TABLE "SCOTT"."CHAMPION" 
   (	"CHAMPNAME" VARCHAR2(30 BYTE), 
	"CHAMPTYPE1" VARCHAR2(30 BYTE), 
	"CHAMPIMG" NUMBER(10,0), 
	"CHAMPTYPE2" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SCOTT"."CHAMPION"."CHAMPNAME" IS '영웅이름';
   COMMENT ON COLUMN "SCOTT"."CHAMPION"."CHAMPTYPE1" IS '영웅타입';
   COMMENT ON COLUMN "SCOTT"."CHAMPION"."CHAMPIMG" IS '영웅이미지';
   COMMENT ON COLUMN "SCOTT"."CHAMPION"."CHAMPTYPE2" IS '영웅타입2';
REM INSERTING into SCOTT.CHAMPION
SET DEFINE OFF;
Insert into SCOTT.CHAMPION (CHAMPNAME,CHAMPTYPE1,CHAMPIMG,CHAMPTYPE2) values ('이렐리아','war.png',1,'top.png');
Insert into SCOTT.CHAMPION (CHAMPNAME,CHAMPTYPE1,CHAMPIMG,CHAMPTYPE2) values ('리신','war.png',2,'jg.png');
Insert into SCOTT.CHAMPION (CHAMPNAME,CHAMPTYPE1,CHAMPIMG,CHAMPTYPE2) values ('조이','mage.png',3,'mid.png');
Insert into SCOTT.CHAMPION (CHAMPNAME,CHAMPTYPE1,CHAMPIMG,CHAMPTYPE2) values ('블리츠크랭크','sup.png',4,'bottom.png');
Insert into SCOTT.CHAMPION (CHAMPNAME,CHAMPTYPE1,CHAMPIMG,CHAMPTYPE2) values ('이즈리얼','attack.png',5,'bottom.png');
Insert into SCOTT.CHAMPION (CHAMPNAME,CHAMPTYPE1,CHAMPIMG,CHAMPTYPE2) values ('레킹볼','탱커',6,'ow_tank.png');
Insert into SCOTT.CHAMPION (CHAMPNAME,CHAMPTYPE1,CHAMPIMG,CHAMPTYPE2) values ('겐지','딜러',7,'ow_attack.png');
Insert into SCOTT.CHAMPION (CHAMPNAME,CHAMPTYPE1,CHAMPIMG,CHAMPTYPE2) values ('UNKOWNS','UNKOWNS',12,'UNKOWNS');
Insert into SCOTT.CHAMPION (CHAMPNAME,CHAMPTYPE1,CHAMPIMG,CHAMPTYPE2) values ('라인하르트','탱커',8,'ow_tank.png');
Insert into SCOTT.CHAMPION (CHAMPNAME,CHAMPTYPE1,CHAMPIMG,CHAMPTYPE2) values ('아나','힐러',9,'ow_support.png');
Insert into SCOTT.CHAMPION (CHAMPNAME,CHAMPTYPE1,CHAMPIMG,CHAMPTYPE2) values ('트레이서','딜러',10,'ow_attack.png');
Insert into SCOTT.CHAMPION (CHAMPNAME,CHAMPTYPE1,CHAMPIMG,CHAMPTYPE2) values ('모이라','힐러',11,'ow_support.png');
--------------------------------------------------------
--  DDL for Index CHAMPION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."CHAMPION_PK" ON "SCOTT"."CHAMPION" ("CHAMPNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CHAMPION
--------------------------------------------------------

  ALTER TABLE "SCOTT"."CHAMPION" ADD CONSTRAINT "CHAMPION_PK" PRIMARY KEY ("CHAMPNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHAMPION
--------------------------------------------------------

  ALTER TABLE "SCOTT"."CHAMPION" ADD CONSTRAINT "CHAMPION_FK2" FOREIGN KEY ("CHAMPIMG")
	  REFERENCES "SCOTT"."CHAMPIMG" ("CHAMPIMGNO") ENABLE;
