--------------------------------------------------------
--  파일이 생성됨 - 화요일-9월-29-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GAME_RECORD
--------------------------------------------------------

  CREATE TABLE "SCOTT"."GAME_RECORD" 
   (	"RECORDNO" NUMBER(10,0), 
	"NICKNAME" VARCHAR2(50 BYTE), 
	"STARTDATE" DATE, 
	"DAMAGE" NUMBER(10,0), 
	"SCORE" NUMBER(10,0), 
	"MVP" CHAR(1 BYTE), 
	"RESULT" CHAR(1 BYTE), 
	"GAMETYPE" VARCHAR2(20 BYTE), 
	"GAMENAME" VARCHAR2(30 BYTE), 
	"CHAMPION" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SCOTT"."GAME_RECORD"."RECORDNO" IS '전적번호';
   COMMENT ON COLUMN "SCOTT"."GAME_RECORD"."NICKNAME" IS '닉네임';
   COMMENT ON COLUMN "SCOTT"."GAME_RECORD"."STARTDATE" IS '게임진행시간';
   COMMENT ON COLUMN "SCOTT"."GAME_RECORD"."DAMAGE" IS '데미지';
   COMMENT ON COLUMN "SCOTT"."GAME_RECORD"."SCORE" IS '스코어';
   COMMENT ON COLUMN "SCOTT"."GAME_RECORD"."MVP" IS '결과등급';
   COMMENT ON COLUMN "SCOTT"."GAME_RECORD"."RESULT" IS '결과';
   COMMENT ON COLUMN "SCOTT"."GAME_RECORD"."GAMETYPE" IS '게임타입';
   COMMENT ON COLUMN "SCOTT"."GAME_RECORD"."GAMENAME" IS '게임명';
   COMMENT ON COLUMN "SCOTT"."GAME_RECORD"."CHAMPION" IS '영웅이름';
   COMMENT ON TABLE "SCOTT"."GAME_RECORD"  IS '게임전적';
REM INSERTING into SCOTT.GAME_RECORD
SET DEFINE OFF;
Insert into SCOTT.GAME_RECORD (RECORDNO,NICKNAME,STARTDATE,DAMAGE,SCORE,MVP,RESULT,GAMETYPE,GAMENAME,CHAMPION) values (1,'배틀그라운드',to_date('20/09/22','RR/MM/DD'),450,1,'1','0','경쟁전','PUBG','UNKOWNS');
Insert into SCOTT.GAME_RECORD (RECORDNO,NICKNAME,STARTDATE,DAMAGE,SCORE,MVP,RESULT,GAMETYPE,GAMENAME,CHAMPION) values (2,'배틀그라운드',to_date('20/09/23','RR/MM/DD'),1250,2,'1','1','경쟁전','PUBG','UNKOWNS');
Insert into SCOTT.GAME_RECORD (RECORDNO,NICKNAME,STARTDATE,DAMAGE,SCORE,MVP,RESULT,GAMETYPE,GAMENAME,CHAMPION) values (3,'배틀그라운드',to_date('20/09/24','RR/MM/DD'),380,3,'1','0','경쟁전','PUBG','UNKOWNS');
Insert into SCOTT.GAME_RECORD (RECORDNO,NICKNAME,STARTDATE,DAMAGE,SCORE,MVP,RESULT,GAMETYPE,GAMENAME,CHAMPION) values (4,'배틀그라운드',to_date('20/09/25','RR/MM/DD'),270,4,'1','0','경쟁전','PUBG','UNKOWNS');
Insert into SCOTT.GAME_RECORD (RECORDNO,NICKNAME,STARTDATE,DAMAGE,SCORE,MVP,RESULT,GAMETYPE,GAMENAME,CHAMPION) values (5,'배틀그라운드',to_date('20/09/26','RR/MM/DD'),740,5,'1','0','경쟁전','PUBG','UNKOWNS');
Insert into SCOTT.GAME_RECORD (RECORDNO,NICKNAME,STARTDATE,DAMAGE,SCORE,MVP,RESULT,GAMETYPE,GAMENAME,CHAMPION) values (6,'리그오브레전드',to_date('20/09/22','RR/MM/DD'),30525,6,'1','0','솔랭','LOL','이렐리아');
Insert into SCOTT.GAME_RECORD (RECORDNO,NICKNAME,STARTDATE,DAMAGE,SCORE,MVP,RESULT,GAMETYPE,GAMENAME,CHAMPION) values (7,'리그오브레전드',to_date('20/09/25','RR/MM/DD'),17927,7,'1','1','솔랭','LOL','리신');
Insert into SCOTT.GAME_RECORD (RECORDNO,NICKNAME,STARTDATE,DAMAGE,SCORE,MVP,RESULT,GAMETYPE,GAMENAME,CHAMPION) values (8,'리그오브레전드',to_date('20/09/27','RR/MM/DD'),52169,8,'1','1','솔랭','LOL','조이');
Insert into SCOTT.GAME_RECORD (RECORDNO,NICKNAME,STARTDATE,DAMAGE,SCORE,MVP,RESULT,GAMETYPE,GAMENAME,CHAMPION) values (9,'리그오브레전드',to_date('20/09/28','RR/MM/DD'),8542,9,'0','0','자유5:5랭크','LOL','블리츠크랭크');
Insert into SCOTT.GAME_RECORD (RECORDNO,NICKNAME,STARTDATE,DAMAGE,SCORE,MVP,RESULT,GAMETYPE,GAMENAME,CHAMPION) values (10,'리그오브레전드',to_date('20/09/29','RR/MM/DD'),40521,10,'1','1','솔랭','LOL','이즈리얼');
Insert into SCOTT.GAME_RECORD (RECORDNO,NICKNAME,STARTDATE,DAMAGE,SCORE,MVP,RESULT,GAMETYPE,GAMENAME,CHAMPION) values (11,'오버워치',to_date('20/09/22','RR/MM/DD'),9042,11,'0','1','경쟁전','OVERWATCH','레킹볼');
Insert into SCOTT.GAME_RECORD (RECORDNO,NICKNAME,STARTDATE,DAMAGE,SCORE,MVP,RESULT,GAMETYPE,GAMENAME,CHAMPION) values (12,'오버워치',to_date('20/09/23','RR/MM/DD'),9042,12,'0','1','경쟁전','OVERWATCH','겐지');
Insert into SCOTT.GAME_RECORD (RECORDNO,NICKNAME,STARTDATE,DAMAGE,SCORE,MVP,RESULT,GAMETYPE,GAMENAME,CHAMPION) values (13,'오버워치',to_date('20/09/24','RR/MM/DD'),9042,13,'0','1','경쟁전','OVERWATCH','라인하르트');
Insert into SCOTT.GAME_RECORD (RECORDNO,NICKNAME,STARTDATE,DAMAGE,SCORE,MVP,RESULT,GAMETYPE,GAMENAME,CHAMPION) values (14,'오버워치',to_date('20/09/25','RR/MM/DD'),9042,14,'0','1','경쟁전','OVERWATCH','아나');
Insert into SCOTT.GAME_RECORD (RECORDNO,NICKNAME,STARTDATE,DAMAGE,SCORE,MVP,RESULT,GAMETYPE,GAMENAME,CHAMPION) values (15,'오버워치',to_date('20/09/26','RR/MM/DD'),9042,15,'0','1','경쟁전','OVERWATCH','트레이서');
Insert into SCOTT.GAME_RECORD (RECORDNO,NICKNAME,STARTDATE,DAMAGE,SCORE,MVP,RESULT,GAMETYPE,GAMENAME,CHAMPION) values (16,'오버워치',to_date('20/09/27','RR/MM/DD'),9042,16,'0','1','경쟁전','OVERWATCH','모이라');
--------------------------------------------------------
--  DDL for Index GAME_RECORD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."GAME_RECORD_PK" ON "SCOTT"."GAME_RECORD" ("RECORDNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table GAME_RECORD
--------------------------------------------------------

  ALTER TABLE "SCOTT"."GAME_RECORD" ADD CONSTRAINT "GAME_RECORD_PK" PRIMARY KEY ("RECORDNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SCOTT"."GAME_RECORD" MODIFY ("GAMENAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GAME_RECORD" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GAME_RECORD" MODIFY ("RECORDNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table GAME_RECORD
--------------------------------------------------------

  ALTER TABLE "SCOTT"."GAME_RECORD" ADD CONSTRAINT "FK_GAMERECORD_GAMENO_PROFILE_G" FOREIGN KEY ("GAMENAME")
	  REFERENCES "SCOTT"."GAME" ("GAMENAME") ENABLE;
  ALTER TABLE "SCOTT"."GAME_RECORD" ADD CONSTRAINT "GAME_RECORD_FK1" FOREIGN KEY ("CHAMPION")
	  REFERENCES "SCOTT"."CHAMPION" ("CHAMPNAME") ENABLE;
  ALTER TABLE "SCOTT"."GAME_RECORD" ADD CONSTRAINT "GAME_RECORD_FK2" FOREIGN KEY ("NICKNAME")
	  REFERENCES "SCOTT"."GAME_PROFILE" ("NICKNAME") ENABLE;
