--------------------------------------------------------
--  파일이 생성됨 - 화요일-9월-29-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GAME_PROFILE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."GAME_PROFILE" 
   (	"GAMENAME" VARCHAR2(50 BYTE), 
	"NICKNAME" VARCHAR2(50 BYTE), 
	"PROFILENO" NUMBER(10,0), 
	"RECORDNO" NUMBER(10,0), 
	"P_RANK" VARCHAR2(100 BYTE), 
	"P_LEVEL" VARCHAR2(100 BYTE), 
	"RANKNAME" VARCHAR2(30 BYTE), 
	"SCORE1" VARCHAR2(20 BYTE), 
	"SCORE2" VARCHAR2(20 BYTE), 
	"SCORE3" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SCOTT"."GAME_PROFILE"."GAMENAME" IS '닉네임';
   COMMENT ON COLUMN "SCOTT"."GAME_PROFILE"."NICKNAME" IS '닉네임';
   COMMENT ON COLUMN "SCOTT"."GAME_PROFILE"."PROFILENO" IS '프로필번호';
   COMMENT ON COLUMN "SCOTT"."GAME_PROFILE"."RECORDNO" IS '전적번호';
   COMMENT ON COLUMN "SCOTT"."GAME_PROFILE"."P_RANK" IS '계급';
   COMMENT ON COLUMN "SCOTT"."GAME_PROFILE"."P_LEVEL" IS '레벨';
   COMMENT ON COLUMN "SCOTT"."GAME_PROFILE"."RANKNAME" IS '랭크이름';
   COMMENT ON COLUMN "SCOTT"."GAME_PROFILE"."SCORE1" IS '스코어1';
   COMMENT ON COLUMN "SCOTT"."GAME_PROFILE"."SCORE2" IS '스코어2';
   COMMENT ON COLUMN "SCOTT"."GAME_PROFILE"."SCORE3" IS '스코어3';
   COMMENT ON TABLE "SCOTT"."GAME_PROFILE"  IS '프로필';
REM INSERTING into SCOTT.GAME_PROFILE
SET DEFINE OFF;
Insert into SCOTT.GAME_PROFILE (GAMENAME,NICKNAME,PROFILENO,RECORDNO,P_RANK,P_LEVEL,RANKNAME,SCORE1,SCORE2,SCORE3) values ('PUBG','배틀그라운드',1,1,'pubg-top.png','314','GrandMaster','4320',null,null);
Insert into SCOTT.GAME_PROFILE (GAMENAME,NICKNAME,PROFILENO,RECORDNO,P_RANK,P_LEVEL,RANKNAME,SCORE1,SCORE2,SCORE3) values ('LOL','리그오브레전드',2,2,'challenger.png','105','Challenger',null,null,null);
Insert into SCOTT.GAME_PROFILE (GAMENAME,NICKNAME,PROFILENO,RECORDNO,P_RANK,P_LEVEL,RANKNAME,SCORE1,SCORE2,SCORE3) values ('OVERWATCH','오버워치',3,3,'ow-top.png','245','TOP500','4250','4430','4120');
--------------------------------------------------------
--  DDL for Index GAME_PROFILE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."GAME_PROFILE_PK" ON "SCOTT"."GAME_PROFILE" ("NICKNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table GAME_PROFILE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."GAME_PROFILE" ADD CONSTRAINT "GAME_PROFILE_PK" PRIMARY KEY ("NICKNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SCOTT"."GAME_PROFILE" MODIFY ("PROFILENO" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GAME_PROFILE" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GAME_PROFILE" MODIFY ("GAMENAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table GAME_PROFILE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."GAME_PROFILE" ADD CONSTRAINT "GAME_PROFILE_FK" FOREIGN KEY ("GAMENAME")
	  REFERENCES "SCOTT"."GAME" ("GAMENAME") ENABLE;
