--------------------------------------------------------
--  파일이 생성됨 - 화요일-9월-29-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBERS
--------------------------------------------------------

  CREATE TABLE "SCOTT"."MEMBERS" 
   (	"NO" NUMBER(30,0), 
	"ID" VARCHAR2(50 BYTE), 
	"PWD" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"POINT" VARCHAR2(30 BYTE) DEFAULT 0, 
	"EMAIL" VARCHAR2(100 BYTE), 
	"IMAGE" VARCHAR2(200 BYTE), 
	"PHONE" VARCHAR2(50 BYTE), 
	"INDATE" DATE DEFAULT sysdate, 
	"LOGGEDDATE" VARCHAR2(20 BYTE) DEFAULT 0, 
	"ADMIN" NUMBER(5,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SCOTT.MEMBERS
SET DEFINE OFF;
Insert into SCOTT.MEMBERS (NO,ID,PWD,NAME,POINT,EMAIL,IMAGE,PHONE,INDATE,LOGGEDDATE,ADMIN) values (2,'123','123','chick','300','chick@naver.com','0','123',to_date('20/09/21','RR/MM/DD'),'20200929',0);
Insert into SCOTT.MEMBERS (NO,ID,PWD,NAME,POINT,EMAIL,IMAGE,PHONE,INDATE,LOGGEDDATE,ADMIN) values (1,'admin','admin','관리자','39499','admin@naver.com','9','000',to_date('20/09/21','RR/MM/DD'),'20200929',1);
--------------------------------------------------------
--  DDL for Index SYS_C007120
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C007120" ON "SCOTT"."MEMBERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MEMBERS
--------------------------------------------------------

  ALTER TABLE "SCOTT"."MEMBERS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SCOTT"."MEMBERS" MODIFY ("PWD" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MEMBERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MEMBERS" MODIFY ("NO" NOT NULL ENABLE);
