--------------------------------------------------------
--  파일이 생성됨 - 화요일-9월-29-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table OVERWATCH
--------------------------------------------------------

  CREATE TABLE "SCOTT"."OVERWATCH" 
   (	"RECORDNO" NUMBER(10,0), 
	"CHAMPNAME" VARCHAR2(20 BYTE), 
	"ACCURACYRATE" VARCHAR2(10 BYTE), 
	"GAMETIME" VARCHAR2(30 BYTE), 
	"WIN" VARCHAR2(20 BYTE), 
	"LOSS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SCOTT"."OVERWATCH"."CHAMPNAME" IS '영웅이름';
   COMMENT ON COLUMN "SCOTT"."OVERWATCH"."ACCURACYRATE" IS '명중률';
   COMMENT ON COLUMN "SCOTT"."OVERWATCH"."GAMETIME" IS '게임시간';
   COMMENT ON COLUMN "SCOTT"."OVERWATCH"."WIN" IS '승리';
   COMMENT ON COLUMN "SCOTT"."OVERWATCH"."LOSS" IS '패배';
   COMMENT ON TABLE "SCOTT"."OVERWATCH"  IS '오버워치 세부전적';
REM INSERTING into SCOTT.OVERWATCH
SET DEFINE OFF;
Insert into SCOTT.OVERWATCH (RECORDNO,CHAMPNAME,ACCURACYRATE,GAMETIME,WIN,LOSS) values (11,'레킹볼','49','22','42','21');
Insert into SCOTT.OVERWATCH (RECORDNO,CHAMPNAME,ACCURACYRATE,GAMETIME,WIN,LOSS) values (12,'겐지','43','19','35','19');
Insert into SCOTT.OVERWATCH (RECORDNO,CHAMPNAME,ACCURACYRATE,GAMETIME,WIN,LOSS) values (13,'라인하르트','42','17','25','16');
Insert into SCOTT.OVERWATCH (RECORDNO,CHAMPNAME,ACCURACYRATE,GAMETIME,WIN,LOSS) values (14,'아나','48','15','23','13');
Insert into SCOTT.OVERWATCH (RECORDNO,CHAMPNAME,ACCURACYRATE,GAMETIME,WIN,LOSS) values (15,'트레이서','44','14','29','13');
Insert into SCOTT.OVERWATCH (RECORDNO,CHAMPNAME,ACCURACYRATE,GAMETIME,WIN,LOSS) values (16,'모이라','47','14','28','13');
--------------------------------------------------------
--  DDL for Index OVERWATCH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."OVERWATCH_PK" ON "SCOTT"."OVERWATCH" ("RECORDNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table OVERWATCH
--------------------------------------------------------

  ALTER TABLE "SCOTT"."OVERWATCH" ADD CONSTRAINT "OVERWATCH_PK" PRIMARY KEY ("RECORDNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SCOTT"."OVERWATCH" MODIFY ("RECORDNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table OVERWATCH
--------------------------------------------------------

  ALTER TABLE "SCOTT"."OVERWATCH" ADD CONSTRAINT "FK_OVERWATCH_CHAMPNAME" FOREIGN KEY ("CHAMPNAME")
	  REFERENCES "SCOTT"."CHAMPION" ("CHAMPNAME") ENABLE;
  ALTER TABLE "SCOTT"."OVERWATCH" ADD CONSTRAINT "FK_OVERWATCH_RECORDNO" FOREIGN KEY ("RECORDNO")
	  REFERENCES "SCOTT"."GAME_RECORD" ("RECORDNO") ENABLE;
