--------------------------------------------------------
--  파일이 생성됨 - 화요일-9월-29-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PUBG
--------------------------------------------------------

  CREATE TABLE "SCOTT"."PUBG" 
   (	"RECORDNO" NUMBER(10,0), 
	"ACCURACYRATE" VARCHAR2(10 BYTE), 
	"WALKING" VARCHAR2(20 BYTE), 
	"DRIVE" VARCHAR2(20 BYTE), 
	"RANKING" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SCOTT"."PUBG"."RECORDNO" IS '전적번호';
   COMMENT ON COLUMN "SCOTT"."PUBG"."ACCURACYRATE" IS '명중률';
   COMMENT ON COLUMN "SCOTT"."PUBG"."WALKING" IS '걸은거리';
   COMMENT ON COLUMN "SCOTT"."PUBG"."DRIVE" IS '차량탑승거리';
   COMMENT ON TABLE "SCOTT"."PUBG"  IS '배틀그라운드 세부전적';
REM INSERTING into SCOTT.PUBG
SET DEFINE OFF;
Insert into SCOTT.PUBG (RECORDNO,ACCURACYRATE,WALKING,DRIVE,RANKING) values (1,'43','1.5','4.49','15');
Insert into SCOTT.PUBG (RECORDNO,ACCURACYRATE,WALKING,DRIVE,RANKING) values (2,'39','4.2','1.54','1');
Insert into SCOTT.PUBG (RECORDNO,ACCURACYRATE,WALKING,DRIVE,RANKING) values (3,'45','3.4','1.21','21');
Insert into SCOTT.PUBG (RECORDNO,ACCURACYRATE,WALKING,DRIVE,RANKING) values (4,'38','1.5','1.00','3');
Insert into SCOTT.PUBG (RECORDNO,ACCURACYRATE,WALKING,DRIVE,RANKING) values (5,'35','2.5','2.25','7');
--------------------------------------------------------
--  DDL for Index PUBG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."PUBG_PK" ON "SCOTT"."PUBG" ("RECORDNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PUBG
--------------------------------------------------------

  ALTER TABLE "SCOTT"."PUBG" ADD CONSTRAINT "PUBG_PK" PRIMARY KEY ("RECORDNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
